### Numpy

Numpy is short for numerical python which is the fundamental package required for high performance scientific computing and data analysis.     
It is the foundation on which nearly all of the higher level packages are built from.
ndarray is one of the key features of NumPy which stands for N-dimensional array object.  
Arrays enable us to perform mathematical functions on whole blocks of data using similar syntax to the equivalent operations.

Numpy provides:
      ndarray a fast and space efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting operations.   
      Standard mathematical functions for fast operations on entire arrays of data without having to write loops
      Tools for working with memory mapped files.
      Linear algebra,random number generation and fourier transformation capabilitities.
      
Data analysis applications:
      Common array algorithms like sorting,unique and set operations.  
      Efficient descriptive statistics and aggregation/summarization data.
      Group wise data manipulation(aggregation,transformation,functions,applications).
      


### The NumPy ndarray
This is the N-dimensional array object or ndarray which is fast, flexible container for large data sets in python.   
Arrays enable you to perform mathematical functions on whole blocks of data using similar syntax to the equivalent operations between scalar elements.   
An ndarray is a generic multidimensional container for homogeneous data: that is all of the elements must be of the same type.

### Creating Arrays
The easiet way to create an array is to use the array function.

In [1]:
#import numpy package as np
import numpy as np

a = [1,2,3,4,5,6,7]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [2]:
#nested sequences like a list of equal length will be converted into multidimensional array
b = [[1,2,3,4,5],[7,8,9,0,2]]
arr1 = np.array(b)
arr1

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 0, 2]])

In [3]:
#getting the number of dimensions in a multidimensional array we use the ndim function
arr1.ndim

2

In [4]:
#getting the shape of the multidimensional array use the shape method
arr1.shape

(2, 5)

In [5]:
#getting the datatype
arr1.dtype

dtype('int32')

In [6]:
#other functions for creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.empty((2,3,4))

array([[[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
         1.11261926e-307],
        [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
         1.02359984e-306],
        [1.33510679e-306, 2.22522597e-306, 1.33511018e-306,
         6.23057689e-307]],

       [[1.86921279e-306, 8.90098127e-307, 1.78020848e-306,
         1.60219035e-306],
        [1.42418172e-306, 2.04712906e-306, 7.56589622e-307,
         1.11258277e-307],
        [8.90111708e-307, 3.22643519e-307, 9.79103798e-307,
         2.46155235e-312]]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#convert input to ndarray but do not copy if the input is already an ndarray
np.asarray(10)

array(10)

In [11]:
np.ones_like(10)

array(1)

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros_like(10)

array(0)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Numpy Data Types 

A datatype or dtype is a special object containing the information the ndarray needs to interpret

In [16]:
arr = np.array([1,2,3,4,] ,dtype = np.float64)
arr.dtype

dtype('float64')

You can explicity convert or cast an array from one dtype to another using the astype method

In [17]:
float_arr = arr.astype(np.int64)
float_arr.dtype

dtype('int64')

In the above example floating point numbers were cast to integers  
Should you have an array of strings representing numbers, you can use astype to convert them to numeric form

In [18]:
numeric_strings = np.array(['5.89','4.89','9.000'])
numeric_strings.astype(float)

array([5.89, 4.89, 9.  ])

In [19]:
numeric_strings.dtype

dtype('<U5')

In [20]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
calibers = np.array([3.45,.567,.890,.453,.789], dtype = np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Operations Between  Arrays and Scalars

Arrays are important because they enable you to express batch operations on data without writing any for loops.  
This is usually called vectorization

In [22]:
arr = np.array([[1.23,2,5],[4,6,7]])
arr

array([[1.23, 2.  , 5.  ],
       [4.  , 6.  , 7.  ]])

In [23]:
arr*arr

array([[ 1.5129,  4.    , 25.    ],
       [16.    , 36.    , 49.    ]])

Arithmetic operations with scalars are as you would expect,propagating the value to each element:
    

In [24]:
1/arr

array([[0.81300813, 0.5       , 0.2       ],
       [0.25      , 0.16666667, 0.14285714]])

Operations between differently sized arrays is called broadcasting.

### Basic Indexing and Slicing

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5]

5

In [27]:
arr[5:8]

array([5, 6, 7])

In [28]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

If you can assign a scalar value to a slice as in arr[5:8] = 12, the value is propagated to the entire selection.  
This means that the data is not copied and any modifications to the view will be reflected in the source array:

In [29]:
arr_slice = arr[5:8]

In [30]:
arr_slice[1] = 124567

In [31]:
arr

array([     0,      1,      2,      3,      4,     12, 124567,     12,
            8,      9])

In [32]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])